version: 0.0
os: linux

files:
  - source: .
    destination: /home/ubuntu/projects/deepen

hooks:
  AfterInstall:
   - location: after-install.sh
     timeout: 300
  ApplicationStart:
   - location: application-start.sh
     timeout: 300
